training:
  num_epochs: 100
  batch_size: 32
  num_workers: 4
  patience: 10
  log_val_loss: True
  patience_objective: "WER"
  save_path: "/home/anhkhoa/anhkhoa/PhonoASR/saves"
  train_path : "/home/anhkhoa/anhkhoa/dataset/train_word.json"
  dev_path : "/home/anhkhoa/anhkhoa/dataset/test_word.json"
  test_path : "/home/anhkhoa/anhkhoa/dataset/test_word.json"
  vocab_path : "/home/anhkhoa/anhkhoa/dataset/word_vocab_vivos.json"
  wave_path: "/home/anhkhoa/dataset/voices"
  reload: False
  reload_mode: 'best'
  logg : "/home/anhkhoa/anhkhoa/PhonoASR/logs/char_speech-transformer.log"
  ctc_weight: 0
  result: "/home/anhkhoa/anhkhoa/PhonoASR/result-speech-transformer.json"
  type: "word"
  type_training : "ce"


infer: 
  type_decode: 'normal' # mtp_stack/mtp
  max_output_len: 1024

optim:
  type: adam
  lr: 0.001
  weight_decay: 0.0001
  decay_rate: 0.5

scheduler:
  lr: 0.001
  n_warmup_steps: 25000

model:
  enc:
    subsampling:
      num_blocks: 3
      num_layers_per_block: 2
      out_channels: [64, 64, 64]
      kernel_sizes: [5, 5, 1]
      strides: [2, 2, 1]
      residuals: [ False, False, True]
      dropout: 0.1 
    in_features: 1280
    n_layers: 12
    d_model: 144
    ff_size: 1024
    h: 4
    p_dropout: 0.1
    type: 'SpeechTransformer'
  dec:
    type: 'base'
    n_layer: 4
    d_model: 144
    ff_size: 1024
    n_head: 4
    dropout: 0.1
    k: 1
  model_name: "SpeechTransformer"




