model:
  enc:
    subsampling_type: conv_frontend
    subsampling:
      num_blocks: 3
      num_layers_per_block: 2
      out_channels: [8,  16, 32]
      kernel_sizes: [3, 3, 3]
      strides: [1, 2, 2]
      residuals: [ True, True, True]
      dropout: 0.1 
    input_dim: 80
    encoder_dim: 256
    d_model : 256
    num_attention_heads: 8
    feed_forward_expansion_factor : 4
    dropout_rate: 0.1
    conv_kernel_size: 31
    num_encoder_layers: 1
    output_dim: 256
    in_channels: 1
    out_channels: 32
    type : 'Conformer'
    projection_dim : 640
    output_dim : 320
  dec: 
    embedding_size: 144
    hidden_size: 512
    output_size: 320
    n_layers : 4
    type: "transducer"
    k: 1
    dropout: 0.2
  joint:
    input_size: 640
    inner_size: 512
  model_name : 'Conformer'
  k: 1

training:
  batch_size: 32
  num_workers: 4
  save_path: "PhonoASR/saves"
  train_path : "../dataset/LSVSC_train_char.json"
  dev_path : "../dataset/LSVSC_valid_char.json"
  test_path : "../dataset/LSVSC_test_char.json"
  vocab_path : "../dataset/char_vocab_lsvsc.json"
  wave_path: "../dataset/LSVSC_100/data"
  reload: False
  reload_mode: 'best'
  logg : "PhonoASR/logs/tasa.log"
  ctc_weight: 0
  result: "PhonoASR/result-tasa.json"
  type: "word"
  type_training: "transducer"
  wave_path: "/home/anhkhoa/dataset/voices"
  is_specAugment: True
  specAugment:
    mF : 2
    F: 27
    mT : 10
    pS : 0.05
    
infer: 
    type_decode: "normal"
    max_output_len: 1024
    
optim:
  type: adam
  lr: 0.001
  weight_decay: 0.0001
  decay_rate: 0.5

scheduler:
  lr_initial: 0.001
  n_warmup_steps: 15000

loss:
    blank: 5


  