training:
  epochs: 100
  batch_size: 1
  num_workers: 4
  save_path: "/home/anhkhoa/anhkhoa/PhonoASR/saves"
  train_path : "/home/anhkhoa/anhkhoa/dataset/train_word.json"
  dev_path : "/home/anhkhoa/anhkhoa/dataset/test_word.json"
  test_path : "/home/anhkhoa/anhkhoa/dataset/test_word.json"
  vocab_path : "/home/anhkhoa/anhkhoa/dataset/word_vocab_vivos.json"
  reload: False
  logg: "/home/anhkhoa/anhkhoa/PhonoASR/Conformer.log"
  # ctc_weight: 0.3
  result: "/home/anhkhoa/anhkhoa/PhonoASR/Conformer_word_result.txt"
  type: "word"
  type_training: "transducer"
  wave_path: "/home/anhkhoa/dataset/voices"
  n_mels : 160
  
optim:
  type: adam
  lr: 1
  weight_decay: 0.0001
  decay_rate: 0.5

scheduler:
  lr_initial: 1
  n_warmup_steps: 15000

model:
  enc:
    input_size: 160
    hidden_size: 320
    d_model: 256
    n_layers: 8
    dropout: 0.2
    bidirectional: True
    type: 'RNNT'
    output_size: 256  
    output_dim : 320
  dec:
    embedding_size: 256
    hidden_size: 512
    output_size: 320
    n_layers : 1
    type: "transducer"
    k: 1
<<<<<<< HEAD
=======
    dropout : 0.2
>>>>>>> 0435abc8ddc7ebf7cb1ac0c2081776fb7261db57
  joint:
    input_size: 640
    inner_size: 512
  model_name: "RNNT"

infer:
  type_decode: mtp_stack

rnnt_loss:
  blank: 4
  reduction: "mean"  


