model:
  enc: 
    type : 'SAA'
    n_head: 8
    input_dim: 80               
    d_model: 256       
    dropout: 0.2
    n_layer: 3
  dec: 
    type: 'saa_dec'
    embed_dim: 128
    d_hidden: 256
    num_layers: 3
    embed_dropout: 0.2
    var_dropout: 0.1
    k: 1
  model_name: 'SAA_W2I_VIVOS'

training:
  epochs: 100
  batch_size: 16
  save_path: "/datastore/npl/Speech2Text/PhonoASR/saves"
  train_path : "/datastore/npl/Speech2Text/dataset/train_word.json"
  dev_path : "/datastore/npl/Speech2Text/dataset/test_word.json"
  test_path : "/datastore/npl/Speech2Text/dataset/test_word.json"
  vocab_path : "/datastore/npl/Speech2Text/dataset/word_vocab_vivos.json"
  wave_path: "/datastore/npl/Speech2Text/dataset/voices"
  logg : "/datastore/npl/Speech2Text/PhonoASR/logs/ssa.log"
  result: "/datastore/npl/Speech2Text/PhonoASR/result-ssa-phoneme.txt"
  reload: False
  reload_mode: 'best'
  ctc_weight: 0
  type_training: 'ce'

infer: 
  type_decode: 'normal' # mtp_stack/mtp

optim:
  type: adam
  lr: 0.0003

scheduler:
  lr: 0.0003
  n_warmup_steps: 15000

loss:


  