training:
  epochs: 100
  batch_size: 2
  num_workers: 4
  save_path: "/home/anhkhoa/anhkhoa/PhonoASR/saves"
  train_path : "/home/anhkhoa/anhkhoa/dataset/train_word.json"
  dev_path : "/home/anhkhoa/anhkhoa/dataset/test_word.json"
  test_path : "/home/anhkhoa/anhkhoa/dataset/test_word.json"
  vocab_path : "/home/anhkhoa/anhkhoa/dataset/word_vocab_vivos.json"
  reload: False
  logg: "/home/anhkhoa/anhkhoa/PhonoASR/Conformer.log"
  # ctc_weight: 0.3
  result: "/home/anhkhoa/anhkhoa/PhonoASR/Conformer_word_result.txt"
  type: "word"
  type_training: "transducer"
  wave_path: "/home/anhkhoa/dataset/voices"

infer:
  type_decode: mtp_stack

optim:
  type: adam
  lr: 1
  weight_decay: 0.0001
  decay_rate: 0.5

scheduler:
  lr_initial: 0.001
  n_warmup_steps: 25000

model:
  enc:
    in_features: 200
    n_layer: 8
    d_model: 256
    ff_size: 1024
    h: 8
    p_dropout: 0.3
    type: "TransformerTransducer"
    output_dim: 320
  dec: 
    embedding_size: 256
    hidden_size: 512
    output_size: 320
    n_layers : 1
    type: "transducer"
    k: 1
    dropout : 0.2
  joint:
    input_size: 640
    inner_size: 512
  model_name: "TransformerTransducer"

rnnt_loss: