training:
  epochs: 100
  batch_size: 16
  save_path: "/home/anhkhoa/PhonoASR/saves"
  train_path : "/home/anhkhoa/transformer_transducer_speeQ/data/train_phoneme.json"
  dev_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_phoneme.json"
  test_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_phoneme.json"
  vocab_path : "/home/anhkhoa/transformer_transducer_speeQ/data/vocab_phoneme.json"
  reload: False
  logg : "/home/anhkhoa/PhonoASR/logs/ConvRNNT.log"
  ctc_weight: 0.3
  result: "/home/anhkhoa/PhonoASR/result.txt"
  type: "word"
  type_training : "ce"
  
optim:
  type: adam
  lr: 0.001
  weight_decay: 0.0001
  decay_rate: 0.5

scheduler:
  lr_initial: 0.001
  n_warmup_steps: 15000

model:
  enc:
    local_cnn_encoder: 
        kernel_size: 5
        stride: 1
        feature_dim: 80
        dim_out: 160
    global_cnn_encoder:
        n_layers: 1
        kernel_size_pw: 1
        kernel_size_dw: 3
        stride: 1
        input_dim: 160  
        hidden_dim: 320
        n_dropout: 0.3
    cnn_enc_out: 160
    hidden_size: 320
    output_size: 320
    n_layers: 1
    dropout: 0.2
    bidirectional: True
    name: 'ConvRNNT'
  dec:
    n_layer: 3
    d_model: 256
    ff_size: 1024
    n_head: 4
    dropout: 0.1
    k: 3
  model_name: "ConvRNNT"

rnnt_loss:
  blank: 4
  reduction: "mean"  


