training:
  # epochs: 100
  batch_size: 2
  num_workers: 4
  save_path: "/home/anhkhoa/PhonoASR/saves"
  train_path : "/home/anhkhoa/transformer_transducer_speeQ/data/train_w2i.json"
  dev_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_w2i.json"
  test_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_w2i.json"
  vocab_path : "/home/anhkhoa/transformer_transducer_speeQ/data/vocab_w2i.json"
  wave_path: "/home/inomar01/nlp@uit/PhonoASR/dataset/LSVSC_100/data"
  reload: False
  logg : "/home/anhkhoa/PhonoASR/logs/rnnt.log"
  result: "/home/anhkhoa/PhonoASR/result-rnnt.json"
  ctc_weight: 0.3
  type: "word"
  type_training : "transducer"
  
optim:
  type: adam
  lr: 1
  weight_decay: 0.0001
  decay_rate: 0.5

scheduler:
  lr_initial: 1
  n_warmup_steps: 15000

model:
  enc:
    input_size: 80
    hidden_size: 320
    d_model: 256
    n_layers: 1
    dropout: 0.2
    bidirectional: True
    type: 'RNNT'
    output_size: 256  
    output_dim : 320
  dec:
    embedding_size: 256
    hidden_size: 512
    output_size: 320
    n_layers : 1
    type: "transducer"
    k: 1
  joint:
    input_size: 640
    inner_size: 512
  model_name: "RNNT"
  d_model: 256

infer:
  type_decode: mtp_stack

rnnt_loss:
  blank: 4
  reduction: "mean"  


