model:
  enc: 
    n_head: 8
    d_model: 160               
    d_hidden: 256       
    dropout: 0.2
    n_layer: 3
  dec: 
    embed_dim: 128
    d_hidden: 256
    num_layers: 2
    embed_dropout: 0.2
    var_dropout: 0.1 
    n_head: 8
    d_model: 160
    dropout: 0.2
    n_layer: 1
    max_len: 400
  feature_dim: 160   # sync with dataset.py
  name : 'SAA'
  share_weight: False
  pad_id: 0
  sos_id: 1
  eos_id: 2
  blank_id: 4
  k: 3


training:
  epochs: 100
  batch_size: 8
  accumulation_steps: 1
  save_path: "/home/llogn/workspace/phonoasr/saves"
  train_path : "/mnt/c/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/train_phoneme.json"
  dev_path : "/mnt/c/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/test_phoneme.json"
  test_path : "/mnt/c/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/test_phoneme.json"
  vocab_path : "/mnt/c/paper/raw_data/Vietnamese-Speech-to-Text-datasets/ViVOS/vocab_phoneme.json"
  logg: "/home/llogn/workspace/phonoasr/logs/saa_log.log"
  infer_path: "/home/llogn/workspace/phonoasr/logs/saa_infer.log"
  reload: False
  ctc_weight: 0.4

optim:
  # type: sgd
  # lr: 0.0005
  # momentum: 0.9
  # weight_decay: 0
  # begin_to_adjust_lr: 60
  # nesterov: None
  # decay_rate: 0.5

  type: adam
  lr: 0.0003
  weight_decay: 0.0
  decay_rate: 0.5

scheduler:
  lr_initial: 0.0003
  n_warmup_steps: 15000

loss:
  # type: cross_entropy 
  # blank: 4
  # reduction: mean
  # label_smoothing: 0.1

  type: kldiv 
  reduction: batchmean
  
  ctc_weight: 0.4
  ctc_reduction: mean

  