model:
  enc: 
    n_head: 8
    d_model: 80               
    d_hidden: 256       
    dropout: 0.2
    n_layer: 8
    name : 'SAA'
  dec: 
    n_layer: 1
    d_model: 256
    ff_size: 1024
    n_head: 4
    dropout: 0.1
    k: 3
  model_name: 'SAA'
  d_model: 256

training:
  epochs: 100
  batch_size: 16
  save_path: "/home/inomar01/nlp@uit/PhonoASR/saves"
  train_path : "/home/inomar01/nlp@uit/PhonoASR/dataset/LSVSC_train_phoneme.json"
  dev_path : "/home/inomar01/nlp@uit/PhonoASR/dataset/LSVSC_valid_phoneme.json"
  test_path : "/home/inomar01/nlp@uit/PhonoASR/dataset/LSVSC_test_phoneme.json"
  vocab_path : "/home/inomar01/nlp@uit/PhonoASR/dataset/phoneme_vocab_lsvsc.json"
  wave_path: "/home/inomar01/nlp@uit/PhonoASR/dataset/LSVSC_100/data"
  logg : "/home/inomar01/nlp@uit/PhonoASR/logs/ssa.log"
  result: "/home/inomar01/nlp@uit/PhonoASR/result-ssa.json"
  reload: False
  ctc_weight: 0.4
  type_training: 'ce'
  type: "word"

optim:
  # type: sgd
  # lr: 0.0005
  # momentum: 0.9
  # weight_decay: 0
  # begin_to_adjust_lr: 60
  # nesterov: None
  # decay_rate: 0.5

  type: adam
  lr: 1
  weight_decay: 0.0
  decay_rate: 0.5

scheduler:
  lr_initial: 1
  n_warmup_steps: 15000

infer:
  type_decode: "mtp_stack"


  