training:
  epochs: 100
  batch_size: 4
  save_path: "/home/anhkhoa/PhonoASR/saves"
  train_path : "/home/anhkhoa/transformer_transducer_speeQ/data/train_phoneme.json"
  dev_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_phoneme.json"
  test_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_phoneme.json"
  vocab_path : "/home/anhkhoa/transformer_transducer_speeQ/data/vocab_phoneme.json"
  reload: False
  logg : "/home/anhkhoa/PhonoASR/logs/TransformerTransducer.log"
  ctc_weight: 0.3
  result: "/home/anhkhoa/PhonoASR/result_2.txt"
  type: "word"
  type_training : "ce"

optim:
  type: sgd 
  lr: 0.0008
  weight_decay: 0.0001
  momentum: 0.9
  decay_rate: 0.5
  nesterov: None

scheduler:
  lr_initial: 0.0003
  n_warmup_steps: 25000

model:
  enc:
    in_features: 80
    n_layer: 3
    d_model: 256
    ff_size: 1024
    h: 8
    p_dropout: 0.3
    name: "TransformerTransducer"
  dec:
    n_layer: 3
    d_model: 256
    ff_size: 1024
    n_head: 4
    dropout: 0.1
    k: 3
  model_name: "TransformerTransducer"

rnnt_loss: